//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fopro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fopro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards=TSA guidelines now prohibit __________ on airplanes.&lt;&gt;It&apos;s a pity that kids these days are all getting involved with __________.&lt;&gt;In 1,000 years, when paper money is but a distant memory, __________ will be our currency.&lt;&gt;Major League Baseball has banned __________ for giving players an unfair advantage.&lt;&gt;What is Batman&apos;s guilty pleasure?&lt;&gt;Next from J.K. Rowling: Harry Potter and the Chamber of __________.&lt;&gt;I&apos;m sorry, Professor, but I couldn&apos;t complete my homework because of __________.&lt;&gt;What did I br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bcards {
            get {
                return ResourceManager.GetString("bcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cards=A Gypsy curse.&lt;&gt;A moment of silence.&lt;&gt;A sausage festival.&lt;&gt;An honest cop with nothing left to lose.&lt;&gt;Famine.&lt;&gt;Flesh-eating bacteria.&lt;&gt;Flying sex snakes.&lt;&gt;Not giving a shit about the Third World.&lt;&gt;Sexting.&lt;&gt;Shapeshifters.&lt;&gt;Porn stars.&lt;&gt;72 virgins.&lt;&gt;A drive-by shooting.&lt;&gt;A time travel paradox.&lt;&gt;Authentic Mexican cuisine.&lt;&gt;Bling.&lt;&gt;Consultants.&lt;&gt;Crippling debt.&lt;&gt;Daddy issues.&lt;&gt;The Donald Trump Seal of Approval™.&lt;&gt;Dropping a chandelier on your enemies and riding the rope up.&lt;&gt;Former President George W. Bus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wcards {
            get {
                return ResourceManager.GetString("wcards", resourceCulture);
            }
        }
    }
}
